# Generated by Django 3.1.2 on 2020-10-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_task_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subject',
            field=models.CharField(choices=[('T', 'TLE'), ('Math', 'Mathematics'), ('ENG', 'ENGLISH'), ('FIL', 'FILIPINO'), ('MAP', 'MAPEH'), ('SCI', 'SCIENCE'), ('E', 'ESP'), ('AP', 'Araling Panlipunan')], default='T', max_length=5),
        ),
    ]
