# Generated by Django 3.1.2 on 2020-10-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201025_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='subject',
            field=models.CharField(choices=[('TLE', 'TLE'), ('MATH', 'Mathematics'), ('ENGLISH', 'ENGLISH'), ('FILIPINO', 'FILIPINO'), ('MAPEH', 'MAPEH'), ('SCIENCE', 'SCIENCE'), ('ESP', 'ESP'), ('AP', 'Araling Panlipunan')], default='T', max_length=50),
        ),
    ]
