# Generated by Django 3.1.2 on 2020-10-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201025_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='summary',
            field=models.TextField(default='A summary'),
        ),
        migrations.AlterField(
            model_name='task',
            name='subject',
            field=models.CharField(choices=[('TLE', 'TLE'), ('MATH', 'Mathematics'), ('ENGLISH', 'ENGLISH'), ('FILIPINO', 'FILIPINO'), ('MAPEH', 'MAPEH'), ('SCIENCE', 'SCIENCE'), ('ESP', 'ESP'), ('AP', 'Araling Panlipunan')], default='TLE', max_length=50),
        ),
    ]
