# Generated by Django 3.1.2 on 2020-10-29 04:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_tasknote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
