# Generated by Django 3.1.2 on 2020-11-03 07:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201029_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='summary',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
