# Generated by Django 3.1.2 on 2020-11-03 07:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201103_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
